.\" Manpage for morsejs.
.\" Contact zero298@gmail.com to correct anything.
.TH morsejs 1 "19 Jan 2016" "0.1.0" "morsejs man page"
.SH NAME
morsejs \- translate a message to morse code
.SH SYNOPSIS
morsejs [MESSAGE]
.SH DESCRIPTION
morsejs is a morse code translator written in JavaScript using node.js.  The output of the command is an array of signals.
.SH DIAGNOSTICS
The following diagnostics may be issued on stderr:

Please provide a message to translate
.RS
You must supply an input message to translate.
.SH AUTHOR
Stephen K